2025-08-15 17:01:10,730 - dashboard_app - logger_setup:setup_logger:43 - INFO - 服务启动，日志存储目录：Logger/20250815_170110
2025-08-15 17:01:10,850 - dashboard_app - cache_manager:_load_offline_cache:28 - INFO - 成功加载离线缓存，包含 1 个文件缓存
2025-08-15 17:02:40,132 - dashboard_app - app:_load_data:55 - INFO - 从离线缓存加载文件: all_sequence_HLX14B178R0001811_merged.csv
2025-08-15 17:02:50,505 - dashboard_app - navigation_visualization:process_data:39 - INFO - 导航数据处理成功
2025-08-15 17:02:51,030 - dashboard_app - navigation_map_module:process_data:41 - INFO - 导航地图生成耗时: 0.52秒
2025-08-15 17:02:51,030 - dashboard_app - navigation_map_module:process_data:42 - INFO - 成功加载 20 张每日导航地图
2025-08-15 17:02:51,494 - dashboard_app - navigation_visualization:process_data:39 - INFO - 导航数据处理成功
2025-08-15 17:04:44,184 - dashboard_app - navigation_visualization:render_output:150 - ERROR - 导航数据可视化失败: Cannot hash argument 'navi_info' (of type `Handle_csv.scenario.navigation.basic_info.navi_info`) in 'cache_route_timeline'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_resource
def cache_route_timeline(_navi_info, ...):
    ...
```
            
Traceback (most recent call last):
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 619, in _to_bytes
    reduce_data = obj.__reduce__()
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/copyreg.py", line 70, in _reduce_ex
    raise TypeError(f"cannot pickle {cls.__name__!r} object")
TypeError: cannot pickle 'function' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 450, in _make_value_key
    update_hash(
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 169, in update_hash
    ch.update(hasher, val)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 345, in update
    b = self.to_bytes(obj)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 327, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj))
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 624, in _to_bytes
    self.update(h, item)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 345, in update
    b = self.to_bytes(obj)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 327, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj))
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 621, in _to_bytes
    raise UnhashableTypeError() from ex
streamlit.runtime.caching.cache_errors.UnhashableTypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lichen18/Documents/Project/demo/modules/navigation_visualization.py", line 100, in render_output
    plot_buf = cache_route_timeline(self.navi_info)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs, spinner_message)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 234, in _get_or_create_cached_value
    value_key = _make_value_key(
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 458, in _make_value_key
    raise UnhashableParamError(cache_type, func, arg_name, arg_value, exc)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 450, in _make_value_key
    update_hash(
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 169, in update_hash
    ch.update(hasher, val)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 345, in update
    b = self.to_bytes(obj)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 327, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj))
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 624, in _to_bytes
    self.update(h, item)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 345, in update
    b = self.to_bytes(obj)
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 327, in to_bytes
    b = b"%s:%s" % (tname, self._to_bytes(obj))
  File "/Users/lichen18/miniforge3/envs/ic/lib/python3.9/site-packages/streamlit/runtime/caching/hashing.py", line 621, in _to_bytes
    raise UnhashableTypeError() from ex
streamlit.runtime.caching.cache_errors.UnhashableParamError: Cannot hash argument 'navi_info' (of type `Handle_csv.scenario.navigation.basic_info.navi_info`) in 'cache_route_timeline'.

To address this, you can tell Streamlit not to hash this argument by adding a
leading underscore to the argument's name in the function signature:

```
@st.cache_resource
def cache_route_timeline(_navi_info, ...):
    ...
```
            
2025-08-15 17:04:44,605 - dashboard_app - navigation_map_module:process_data:41 - INFO - 导航地图生成耗时: 0.42秒
2025-08-15 17:04:44,606 - dashboard_app - navigation_map_module:process_data:42 - INFO - 成功加载 20 张每日导航地图
